You're correct! The proper Docker push command to upload a Docker image to Docker Hub follows this format:

```bash
docker push pexabo/thanoslistener:tagname
```

In this case, `pexabo` is your Docker Hub username, `thanoslistener` is the image name, and `tagname` is the specific tag you want to push (e.g., `latest` or a build ID).

### Updating the Azure DevOps YAML:
To ensure the `docker push` command is executed correctly in the pipeline, the repository and tag must be formatted properly. Here’s the corrected YAML:

```yaml
trigger:
- main

resources:
- repo: self

variables:
  system.debug: true
  tag: '$(Build.BuildId)'   # Use Build ID as a tag
  imageName: 'pexabo/thanoslistener'   # Full Docker Hub image name with username

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest   # Ubuntu as the agent
    steps:
    # Login to Docker Hub
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'DockerHub'   # Use the Docker Hub service connection

    # Build the Docker image
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'   # Ensure Dockerfile path is correct
        repository: $(imageName)   # Define the repository
        tags: |
          $(imageName):$(Build.BuildId)
          $(imageName):latest

    # Push the Docker image to Docker Hub
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: push
        repository: $(imageName)   # Push the built image to Docker Hub
        tags: |
          $(imageName):$(Build.BuildId)
          $(imageName):latest
```

### Key Points:
- The **`repository`** is set to `pexabo/thanoslistener`, so it matches the required format for Docker Hub.
- The **tags** are set as `$(Build.BuildId)` (which gives a unique tag for each build) and `latest`.
- The **docker push** command in the pipeline will be executed like this:
  ```bash
  docker push pexabo/thanoslistener:$(Build.BuildId)
  docker push pexabo/thanoslistener:latest
  ```

Make sure you also have the Docker Hub service connection correctly configured in Azure DevOps under **Project Settings > Service Connections**.

By applying this YAML configuration, your pipeline should successfully push the Docker image to Docker Hub using the correct image and tag format.